---
title: "Exercicis"
output:
  pdf_document:
    toc: yes
  html_document:
    theme: journal
    toc: yes
---

```{r, echo=FALSE, include=F}
rmd <- list.files(pattern = '*.Rmd', recursive = F, include.dirs = F)
print_text = function(x){
cat('# Tema 2. Variables aleatories \n\n')
sel = substr(rmd, 1, 2) %in% c('t2')
chunks <- paste0("```{r child = '", rmd[sel], "'}\n```\n\n--------------------\n")
cat(chunks, sep = '\n')

cat('# Tema 3. Inferència estadística: intervals de confiança i gràfics de control \n\n')
sel = substr(rmd, 1, 2) %in% c('t3')
chunks <- paste0("```{r child = '", rmd[sel], "'}\n```\n\n--------------------\n")
cat(chunks, sep = '\n')

cat('# Tema 4. Inferència estadística: contrastos d\'hipòtesis \n\n')
sel = substr(rmd, 1, 2) %in% c('t4')
chunks <- paste0("```{r child = '", rmd[sel], "'}\n```\n\n--------------------\n")
cat(chunks, sep = '\n')

cat('# Tema 5. Regressió lineal simple \n\n')
sel = substr(rmd, 1, 2) %in% c('t5')
chunks <- paste0("```{r child = '", rmd[sel], "'}\n```\n\n--------------------\n")
cat(chunks, sep = '\n')

}


print_text()
```

# Tema 2. Variables aleatories 

```{r child = 't2_03.Rmd'}
```

--------------------

```{r child = 't2_04.Rmd'}
```

--------------------

```{r child = 't2_05.Rmd'}
```

--------------------

```{r child = 't2_06.Rmd'}
```

--------------------

```{r child = 't2_07.Rmd'}
```

--------------------

```{r child = 't2_08.Rmd'}
```

--------------------

```{r child = 't2_09.Rmd'}
```

--------------------

```{r child = 't2_10.Rmd'}
```

--------------------

```{r child = 't2_11.Rmd'}
```

--------------------

```{r child = 't2_12.Rmd'}
```

--------------------

# Tema 3. Inferència estadística: intervals de confiança i gràfics de control 

```{r child = 't3_05.Rmd'}
```

--------------------

```{r child = 't3_11.Rmd'}
```

--------------------

```{r child = 't3_14.Rmd'}
```

--------------------

```{r child = 't3_16.Rmd'}
```

--------------------

```{r child = 't3_19.Rmd'}
```

--------------------

```{r child = 't3_20.Rmd'}
```

--------------------

```{r child = 't3_22.Rmd'}
```

--------------------

```{r child = 't3_24.Rmd'}
```

--------------------

# Tema 4. Inferència estadística: contrastos d'hipòtesis 

```{r child = 't4_01.Rmd'}
```

--------------------

```{r child = 't4_06.Rmd'}
```

--------------------

```{r child = 't4_09.Rmd'}
```

--------------------

```{r child = 't4_10.Rmd'}
```

--------------------

```{r child = 't4_11.Rmd'}
```

--------------------

```{r child = 't4_13.Rmd'}
```

--------------------

```{r child = 't4_14.Rmd'}
```

--------------------

```{r child = 't4_18.Rmd'}
```

--------------------

```{r child = 't4_21.Rmd'}
```

--------------------

```{r child = 't4_26.Rmd'}
```

--------------------

```{r child = 't4_28.Rmd'}
```

--------------------

# Tema 5. Regressió lineal simple 

```{r child = 't5_01.Rmd'}
```
